### ISSUE TITLE
Install fails with /dev/sdc (the usb stick!) still in use

### ISSUE THREAD

**Issue by SylvatiCodes** [SystemCrafters/guix-installer#12]
Failure happens when trying to partition on multi distro disk. I have tried only having a root partition and also including an extra /boot/efi (I know, this shouldn't affect but should try as many things as possible within reason).
Both times I have received an 'Unexpected problem' window with a stacktrace. I don't know how to copy this over to github or whatever, so the relevant part, I think, is that it errors out on the USB still in use.

Any ideas of how I can share the full stacktrace/error message if needed?

**Comment by SylvatiCodes** [comment]
So I fixed it. It was either down to using ventoy or because the other os had the efi boot flags. I don't know which one because I tried a USB with only your iso on it, and also switched off the flags for the other efi boot.

Thanks for all the work you put in to helping others into guix/emacs/lisp

**Comment by nicolassilvar** [comment]
Im having a similar issue not able to resolve installong 1.3x.in the same usb medium as the installer

When trying to write partition table

Invoke error
Mkfs.ext4 arguments: ("-F" "/dev/sdb1") exit status: 1 term-signal: #f stop-signal: #f

![IMG_20220818_173055](https://user-images.githubusercontent.com/13126838/185506759-b891049c-a3e5-4f92-b201-510810c5026e.jpg)

**Comment by nicolassilvar** [comment]
https://issues.guix.gnu.org/53143
