### ISSUE TITLE
Network Establishment During GUI Install

### ISSUE THREAD

**Issue by oldmanz** [SystemCrafters/guix-installer#15]
Getting a red error screen on latest release. Error is after a 100% for checking internet connection after selecting wifi network, or selecting wired.  Previous [release](https://github.com/SystemCrafters/guix-installer/releases/tag/v202207080334) works fine.

**Comment by oldmanz** [comment]
Never mind on this.  I just tried again on previous release.  Same issue now.  Must be hardware?

**Comment by daviwil** [comment]
I also get this error occasionally, not sure why it happens.  Possible that the installer might not be properly initializing the connection somehow, or just a driver/hardware issue like you mentioned.

**Comment by oldmanz** [comment]
Thanks for the response!  
I ended up using the standard Guix iso with a wired connection, and added the channels.scm and system.scm changes you provided.  Worked perfectly!
