### ISSUE TITLE
Burn image to usb and boot

### ISSUE THREAD

**Issue by jgarte** [SystemCrafters/guix-installer#2]
Hi!
  
Were you able to `dd` this image onto a usb and run it?

I've been trying to figure out how to get that to work but I've had no luck.

**Comment by daviwil** [comment]
I haven't yet, but the Guix manual says that this is how you do it:

```
$ dd if=guix-installer.iso of=/dev/sdX status=progress
$ sync
```

**Comment by gi-yt** [comment]
there is a flag to get iso format

**Comment by jgarte** [comment]
> there is a flag to get iso format

@gi-yt Are you referring to [this command](https://guix.gnu.org/manual/en/html_node/Building-the-Installation-Image.html)?

`guix system image -t iso9660 gnu/system/install.scm`

@daviwil

Last time I tried `dd'ing` a custom iso image onto my thumbdrive that the above command produced into it didn't boot.

The iso image that it built was in `/gnu/store/...`

I'll try again soon.

I'm trying to make an iso image of the guix system server that is running these services:

https://mumble.libremiami.org
https://donotshake.libremiami.org

I'll publish the configs for those at https://git.sr.ht/~libremiami in the next few days.

**Comment by gi-yt** [comment]
> `guix system image -t iso9660 gnu/system/install.scm
yes @jgarte this is the command i was talking about

**Comment by gi-yt** [comment]
The New release @daviwil published works for the same

**Comment by daviwil** [comment]
I've been using the .iso image this CI workflow produces burned to USB sticks and it works great, haven't had any trouble with it.  Let me know if you have any issues with it @jgarte!
