### ISSUE TITLE
"Devices not supporting free software" blocks installation

### ISSUE THREAD

**Issue by twashing** [SystemCrafters/guix-installer#23]
I've installed GuixOS a few times, trying with the 2 iso releases here. And both installations do not pick up the wifi router.

- The "Jul 14" installer ([Jul 14, 2021](https://github.com/SystemCrafters/guix-installer/releases/tag/v202107150234)) uses the wifi to download extra resources. But the main installation doesn't have the driver or configuration to use the wifi router.
- The "Dec 21" installer ([Dec 21, 2022](https://github.com/SystemCrafters/guix-installer/releases/tag/v202212220321)) fails to run, producing this error: "_Devices not supporting free software were found on your computer_".

This patch looks like the culprit (and current line in `master`).

- https://issues.guix.gnu.org/59003
- https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/installer/newt/welcome.scm#n144

Per the "[Guix as a Complete GNU/Linux System](https://systemcrafters.cc/craft-your-system-with-guix/full-system-install/)" post, I think the nonguix channel is the way to use nonfree firmware and drivers. But the blockage at the installer doesn't let me get to that point.

Is there a way around this? The "[Manual Installation](https://guix.gnu.org/manual/en/html_node/Manual-Installation.html)" doesn't seem to offer a way into the `/etc/config.scm`.

**Comment by twashing** [comment]
Oops, never mind 😅 I got it sorted by ["Editing the generated configuration"](https://systemcrafters.cc/craft-your-system-with-guix/full-system-install/#editing-the-generated-configuration).

**Comment by daviwil** [comment]
Hey Tim, sorry I missed this issue!  Glad you figured it out :)
