### ISSUE TITLE
Wrong, scary warning displayed

### ISSUE THREAD

**Issue by ieure** [SystemCrafters/guix-installer#26]
When I boot the installer, I get a big red screen saying that my hardware requiring non-free firmware won't work.  Except, it does work, because that's the whole point of this installer.

Software shouldn't lie to its users.

**Comment by daviwil** [comment]
This repo merely produces a customized version of the standard Guix installer using the full Linux kernel from the Nonguix channel, I don't control anything about what the Guix installer code is doing.  Patching the installer itself is not straightforward, so I'm not sure how we would be able to get rid of this message just for the sake of this ISO.
